const MATERIAS_POR_SEMESTRE_ETN = {
    "3": [
      "VARIABLE COMPLEJA",
      "CAMPOS ELECTROMAGNÉTICOS",
      "ECUACIONES DIFERENCIALES",
      "CIRCUITOS I",
      "METODOLOGÍA DE LA INVESTIGACIÓN",
      "PROCESOS ESTOCÁSTICOS"
    ],
    "4": [
      "INVESTIGACIÓN OPERATIVA",
      "ELECTRÓNICA ANALÓGICA I",
      "MÉTODOS NUMÉRICOS",
      "CAMPOS ELECTROMAGNÉTICOS",
      "SISTEMAS DIGITALES I",
      "SÍNTESIS DE CIRCUITOS"
    ],
    "5": [
      "ELECTRÓNICA ANALÓGICA II",
      "LÍNEAS DE TRANSMISIÓN Y ANTENAS",
      "SISTEMAS DIGITALES II",
      "CONVERSIÓN ELECTROMAGNÉTICA DE ENERGÍA",
      "SEÑALES Y SISTEMAS"
    ],
    "6": [
      "ELECTRÓNICA ANALÓGICA III",
      "ECONOMÍA PARA LA INGENIERÍA",
      "CONMUTACIÓN DIGITAL",
      "MICROPROCESADORES I",
      "SISTEMAS DE CONTROL I",
      "PROPAGACION Y ENLACES"
    ],
    "7": [
      "SISTEMAS DE CONTROL II",
      "MICROPROCESADORES II",
      "ELECTRÓNICA INDUSTRIAL I",
      "TELECOMUNICACIONES I",
      "SISTEMAS DE COMPUTACIÓN",
      "LEGISLACIÓN PARA INGENIERÍA"
    ],
    "8": [
      "ELECTRÓNICA INDUSTRIAL II",
      "CONTROL Y REGULACIÓN INDUSTRIAL I",
      "PREPARACIÓN Y EVALUACIÓN DE PROYECTOS",
      "PROCESAMIENTO DIGITAL DE SEÑALES",
      "REDES DE COMUNICACIÓN I",
      "TELECOMUNICACIONES II"
    ],
    "9": [
      "CONTROL Y REGULACIÓN INDUSTRIAL II",
      "REDES DE COMUNICACIÓN II",
      "SISTEMAS ENERGÉTICOS",
      "TELECOMUNICACIONES III",
      "TRABAJO DE GRADO I"
    ],
    "10": [
      "ELECTROMEDICINA",
      "SISTEMAS DE CONTROL INDUSTRIAL",
      "TELECOMUNICACIONES AVANZADAS",
      "TELEMÁTICA",
      "TRABAJO DE GRADO II"
    ]
  };
  
  export default MATERIAS_POR_SEMESTRE_ETN;