const MATERIAS_POR_SEMESTRE_AGRO = {
    "3": [
      "ECUACIONES DIFERENCIALES",
      "ESTADISTICA II",
      "FISICOQUIMICA",
      "METODOLOGÍA DE LA INVESTIGACIÓN",
      "QUIMICA ORGANICA",
      "SISTEMAS DE PRODUCCION VEGETAL"
    ],
    "4": [
      "INVESTIGACION OPERATIVA",
      "PRODUCCION DE METABOLITOS",
      "QUÍMICA Y ANALISIS DE ALIMENTOS",
      "SISTEMAS DE PRODUCCION ANIMAL",
      "SISTEMAS DE PRODUCCION VEGETAL",
      "TERMODINAMICA"
    ],
    "5": [
      "ADMINISTRACION DE LA PRODUCCION",
      "BIOTECNOLOGIA",
      "COSTOS AGROINDUSTRIALES",
      "MICROBIOLOGIA AGROINDUSTRIAL",
      "NUTRICION APLICADA A LA AGROINDUSTRIA",
      "OPERACIONES UNITARIAS I"
    ],
    "6": [
      "ECONOMIA PARA INGENIERIA",
      "OPERACIONES UNITARIAS II",
      "SEGURIDAD E HIGIENE AGROINDUSTRIAL",
      "TECNOLOGÍA DE BEBIDAS",
      "TECNOLOGÍA DE CEREALES Y GRANOS",
      "TECNOLOGÍA DE CONSERVACION"
    ],
    "7": [
      "LEGISLACION PARA INGENIERIA",
      "MERCADOTECNIA",
      "SIMULACION Y OPTIMIZACION DE PROCESOS AGROINDUSTRIALES",
      "TECNOLOGÍA DE CARNICOS",
      "TECNOLOGÍA DE FRUTAS Y HORTALIZAS",
      "TECNOLOGÍA DE LACTEOS"
    ],
    "8": [
      "DISEÑO DE PLANTAS AGROINDUSTRIALES",
      "DISEÑO EXPERIMENTAL",
      "PREPARACION Y EVALUACION DE PROYECTOS",
      "TECNOLOGÍA DE ACEITES Y GRASAS",
      "TECNOLOGÍA DE AZUCARES Y DERIVADOS DEL CACAO",
      "TECNOLOGÍA DE CUEROS Y TEXTILES"
    ],
    "9": [
      "COMERCIALIZACION INTERNACIONAL AGROINDUSTRIAL",
      "GESTION AMBIENTAL Y TRATAMIENTOS DE DESECHOS AGROINDUSTRIALES",
      "GESTION Y CONTROL DE CALIDAD",
      "TRABAJO DE GRADO I"
    ]
};

export default MATERIAS_POR_SEMESTRE_AGRO;