const MATERIAS_POR_SEMESTRE_TEC_SUP_SE = {
    "1": [
      "CIRCUITOS I",
      "COMPONENTES E INSTRUMENTOS",
      "FÍSICA APLICADA",
      "MATEMÁTICA APLICADA",
      "PROGRAMACIÓN I"
    ],
    "2": [
      "NINGUNA"
    ],
    "3": [
      "ELECTRÓNICA LINEAL II",
      "INTEGRACIÓN HARDWARE Y SOFTWARE",
      "REDES DE COMUNICACIÓN I",
      "SEGURIDAD INDUSTRIAL Y MEDIO AMBIENTE",
      "SISTEMAS MICROCONTROLADOS",
      "TELECOMUNICACIONES I"
    ],
    "4": [
      "NINGUNA"
    ],
    "5": [
      "ELECTRÓNICA INDUSTRIAL",
      "INSTALACIONES ELECTRICAS",
      "SISTEMA DE COMUNICACION SATELITAL",
      "TRABAJO DE GRADO TECNICO I",
      "TRADUCTORES Y ACTUADORES"
    ],
    "6": [
      "NINGUNA"
    ]
  };
  
  export default MATERIAS_POR_SEMESTRE_TEC_SUP_SE;