const MATERIAS_POR_SEMESTRE = {
  "3": [
    "ANALISIS Y DISEÑO DE SISTEMAS BASADOS EN MICROCONTROLADORES",
    "ECUACIONES DIFERENCIALES",
    "ESTADISTICA II",
    "PROGRAMACION III",
    "METODOLOGIA DE LA INVESTIGACION",
    "DIBUJO PARA LA INGENIERIA",
    "FISICA III"
  ],
  "4": [
    "INGENIERIA DE SISTEMAS",
    "ESTRUCTURA DE DATOS II",
    "METODOS NUMERICOS",
    "BASE DE DATOS I",
    "PROGRAMACION AVANZADA",
    "INVESTIGACION OPERATIVA I",
    "ECONOMIA PARA LA INGENIERIA"
  ],
  "5": [
    "REDES DE COMPUTADORAS I",
    "INTELIGENCIA ARTIFICIAL I",
    "ANALISIS Y DISEÑO DE SISTEMAS II",
    "BASE DE DATOS III",
    "INTERNET DE LAS COSAS",
    "ADMINISTRACION DE SISTEMAS OP. Y SERVIDORES"
  ],
  "6": [
    "REDES DE COMPUTADORAS II",
    "INTELIGENCIA ARTIFICIAL II",
    "ANALISIS Y DISEÑO DE SISTEMAS II",
    "BASE DE DATOS III",
    "INTERNET DE LAS COSAS",
    "ADMINISTRACION DE SISTEMAS OP. Y SERVIDORES",
    "DISEÑO ORGANIZACIONAL"
  ],
  "7": [
    "INGENIERIA DE SOFTWARE I",
    "MODELACION Y SIMULACION DE SISTEMAS",
    "LEGISLACION PARA LA INGENIERIA",
    "SEGURIDAD DE SISTEMAS",
    "REDES DE COMPUTADORAS III",
    "PREP. Y EVALUACION DE PROYECTOS"
  ],
  "8": [
    "INGENIERIA DE SOFTWARE II",
    "REINGENIERIA DE SISTEMAS",
    "PRACTICA EMPRESARIAL",
    "ROBOTICA",
    "INFORMATICA FORENSE"
  ],
  "9": [
    "AUDITORIA DE SISTEMAS",
    "TALLER DE TICS Y SOFTWARE",
    "TRABAJO DE GRADO I"
  ],
  "10": [
    "TALLER DE MODELACION Y SIMULACION",
    "ADMINISTRACION Y DIRECCION DE OPERACIONES",
    "TRABAJO DE GRADO II"
  ]
};

export default MATERIAS_POR_SEMESTRE;