const MATERIAS_POR_SEMESTRE_CIVIL = {
    "3": [
      "ECUACIONES DIFERENCIALES",
      "ESTABILIDAD Y TIPOLOGÍA DE ESTRUCTURAS",
      "GEOLOGÍA",
      "HIDRÁULICA I",
      "MATERIALES DE CONSTRUCCIÓN",
      "TOPOGRAFÍA"
    ],
    "4": [
      "ELECTROTECNIA",
      "ESTRUCTURAS ISOSTÁTICAS",
      "GEOLOGÍA",
      "HIDRÁULICA II",
      "HIDROLOGÍA",
      "MATERIALES DE CONSTRUCCIÓN",
      "MÉTODOS NUMÉRICOS"
    ],
    "5": [
      "ESTRUCTURAS HIPERESTÁTICAS",
      "INGENIERÍA SANITARIA I",
      "MECÁNICA DE SUELOS I",
      "MEDIOAMBIENTE",
      "OBRAS HIDRÁULICAS I",
      "RESISTENCIA DE MATERIALES"
    ],
    "6": [
      "ANÁLISIS MATRICIAL DE ESTRUCTURAS",
      "ECONOMIA PARA LA INGENIERIA",
      "ESTRUCTURAS DE HORMIGÓN ARMADO I",
      "INGENIERÍA DE TRÁFICO Y VIALIDAD",
      "INGENIERÍA SANITARIA II",
      "MECÁNICA DE SUELOS II",
      "OBRAS HIDRÁULICAS II"
    ],
    "7": [
      "CARRETERAS",
      "CONSTRUCCIÓN DE VIVIENDAS Y EDIFICIOS",
      "ESTRUCTURAS DE HORMIGÓN ARMADO II",
      "ESTRUCTURAS DE MADERA",
      "INSTALACIONES DOMICILIARIAS E INDUSTRIALES",
      "LEGISLACIÓN PARA LA INGENIERÍA",
      "PLANTAS DE TRATAMIENTO"
    ],
    "8": [
      "ESTRUCTURAS DE HORMIGÓN PRE ESFORZADO",
      "ESTRUCTURAS METÁLICAS",
      "FUNDACIONES",
      "MAQUINARIA Y EQUIPO",
      "PAVIMENTOS",
      "PREPARACIÓN Y EVALUACIÓN DE PROYECTOS"
    ],
    "9": [
      "PRESUPUESTOS, CRONOGRAMAS, ADMINISTRACIÓN, DIRECCIÓN Y PUENTES",
      "TRABAJO DE GRADO I",
      "VÍAS DE TRANSPORTE (AEROPUERTOS Y VÍAS FÉRREAS)"
    ],
    "10": [
      "TRABAJO DE GRADO II"
    ]
};

export default MATERIAS_POR_SEMESTRE_CIVIL;