const MATERIAS_POR_SEMESTRE_COM = {
    "1": [
      "ADMINISTRACIÓN",
      "ALGEBRA",
      "CÁLCULO I",
      "CONTABILIDAD BÁSICA",
      "ECONOMIA"
    ],
    "2": [
      "ÁLGEBRA LINEAL Y TEORIA MATRICIAL",
      "CÁLCULO II",
      "CONTABILIDAD INTERMEDIA",
      "ESTADÍSTICA I",
      "MICROECONOMIA"
    ],
    "3": [
      "ADMINISTRACIÓN DEL TALENTO HUMANO",
      "CONTABILIDAD DE COSTOS",
      "ECUACIONES DIFERENCIALES",
      "ESTADISTICA II",
      "METODOLOGIA DE LA INVESTIGACION",
      "MICROECONOMÍA II"
    ],
    "4": [
      "INVESTIGACION OPERATIVA I",
      "MACROECONOMIA I",
      "MARKETING ESTRATEGICO I",
      "MATEMATICAS FINANCIERAS",
      "METODOS NUMERICOS",
      "PRESUPUESTOS Y CONTROL"
    ],
    "5": [
      "ECONOMETRIA I",
      "FINANZAS I",
      "INVESTIGACION DE MERCADOS",
      "INVESTIGACION OPERATIVA II",
      "MACROECONOMIA II",
      "MARKETING ESTRATEGICO II"
    ],
    "6": [
      "ECONOMETRIA II",
      "ECONOMIA EMPRESARIAL",
      "FINANZAS II",
      "LEGISLACION PARA INGENIERIA",
      "MARKETING DE SERVICIOS",
      "ORGANIZACIÓN INDUSTRIAL"
    ],
    "7": [
      "ADMINISTRACION DE LA PRODUCCION",
      "ADMINISTRACION DE VENTAS",
      "ADMINISTRACION PUBLICA",
      "ANALISIS CUANTITATIVO DECISIONAL",
      "COMERCIO EXTERIOR E INTERNACIONAL",
      "MERCADOS E INSTITUCIONES FINANCIERAS"
    ],
    "8": [
      "ADMINISTRACION LOGISTICA",
      "ECONOMIA MONETARIA Y FISCAL",
      "EMPRENDEDURISMO",
      "HABILIDADES PERSONALES Y DIRECTIVAS",
      "MODELADO Y SIMULACION",
      "PREPARACION Y EVALUACION DE PROYECTOS"
    ],
    "9": [
      "ADMINISTRACION DE PROYECTOS",
      "JUEGO DE NEGOCIOS",
      "PLANIFICACION ESTRATEGICA DE MARKETING",
      "TRABAJO DE GRADO I"
    ],
    "10": [
      "TOPICOS DE MARKETING",
      "TRABAJO DE GRADO II",
      "VALORES Y SEGUROS"
    ]
};

export default MATERIAS_POR_SEMESTRE_COM;