const MATERIAS_POR_SEMESTRE_BASICAS = {
    "1": [
      "ALGEBRA",
      "CALCULO I",
      "DIBUJO PARA INGENIERÍA",
      "FÍSICA I",
      "PROGRAMACIÓN I",
      "QUIMICA APLICADA",
      "QUÍMICA GENERAL"
    ],
    "2": [
      "ALGEBRA LINEAL Y TEORÍA MATRICIAL",
      "CALCULO II",
      "COMPONENTES, INSTRUMENTACION ELECTRONICA Y ARQUITECTURA DE COMPUTADORAS",
      "ESTADÍSTICA I",
      "FÍSICA II",
      "PROGRAMACIÓN",
      "PROGRAMACIÓN II"
    ]
};

export default MATERIAS_POR_SEMESTRE_BASICAS;